### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Naereen** [mgba-emu/gbdoc#2]

**Comment by endrift** [comment]
License is CC-BY 4.0. I don't know if there's a license file I can use for that; GitHub certainly doesn't have a template for it.

E] Looks like there's plaintext here: https://creativecommons.org/licenses/by/4.0/legalcode.txt, which I'll add when I have a chance, markdown version is here: https://github.com/idleberg/Creative-Commons-Markdown/blob/master/4.0/by.markdown

**Comment by Naereen** [comment]
http://creativecommons.org/licenses/by/4.0/legalcode.txt

**Comment by endrift** [comment]
Added.
